# Use Cloth Config mod for the descriptions.
---
modules:
  enchantment: true
fallDamageReduction: 0.5
fallDamageThreshold: 20
speedReductionHorizontal: 0.8
speedReductionVertical: 0.8
modifyPathFinding: true
playerOnly: false
alwaysNotViewBlocking: false
alwaysLeafWalking: false
sounds:
  volume: 1.0
  playerOnly: false
